version: '3'
 
services:
  mysql:
    image: mysql:8
    platform: linux/x86_64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: pass1234
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  postgres:
    image: postgres:15
    platform: linux/x86_64
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    platform: linux/x86_64
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: pass1234
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
  elasticsearch:
    restart: always
    image: elasticsearch:8.10.4
    platform: linux/x86_64
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: admin
  kibana:
    restart: always
    image: kibana:8.10.4
    platform: linux/x86_64
    container_name: kibana
    environment:
      XPACK_SECURITY_ENABLED: 'true'
      ELASTICSEARCH_HOSTS: elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: admin

  logstash:
    image: logstash:8.10.4
    container_name: logstash
    volumes:
      - ./logstash-config/:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch
volumes:
  dbdata:
  local_pgdata:
  pgadmin-data:
  elastic-data:
  logstash-config:
